language: java

jdk:
  - oraclejdk8

script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: damianwajser/spring-rest-commons-options
      tags: true
      jdk: oraclejdk8


notifications:
  email:
    - wajser@gmail.com
