language: java

jdk:
  - oraclejdk8

script: mvn --settings .travis/settings.xml clean verify

deploy:
    skip_cleanup: true
    on:
      repo: damianwajser/spring-rest-commons-options
      tags: true
      jdk: oraclejdk8
      branch: CI
      script: mvn --settings .travis/settings.xml clean verify deploy

notifications:
  email:
    - wajser@gmail.com
