sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"

deploy:
    skip_cleanup: true
    on:
      repo: damianwajser/spring-rest-commons-options
      tags: true
      jdk: oraclejdk8
      branch: master

notifications:
  email:
    - wajser@gmail.com
