language: java

jdk:
  - oraclejdk8
script: lala.sh
deploy:
    provider: script
    skip_cleanup: true
    on:
      repo: damianwajser/spring-rest-commons-options
      tags: true
      jdk: oraclejdk8
      branch: CI

notifications:
  email:
    - wajser@gmail.com
